/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package archivosgraficas;

import java.awt.Color;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Usuario
 */
public class ArchivosGraficos extends javax.swing.JFrame {
    
    int[] obrero1 = new int[50]; 
    int[] obrero2 = new int[50];
    int[] obrero3 = new int[50];
    
    /**
     * Creates new form ArchivosGraficos
     */
    public ArchivosGraficos() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leerBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayDatos = new javax.swing.JTextArea();
        organizarBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leerBtn.setText("Leer Archivo");
        leerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerBtnActionPerformed(evt);
            }
        });

        displayDatos.setColumns(20);
        displayDatos.setRows(5);
        displayDatos.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                displayDatosCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(displayDatos);

        organizarBtn.setText("Organizar Datos");
        organizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizarBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Crear Gráfica con los datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(leerBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(organizarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leerBtn)
                    .addComponent(organizarBtn)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerBtnActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser open = new JFileChooser();
            int option = open.showOpenDialog(this);
            File f1 = new File(open.getSelectedFile().getPath());
            try (FileReader fr = new FileReader(f1)) {
                BufferedReader br = new BufferedReader(fr);
                String s;
                while((s=br.readLine())!=null) {
                    displayDatos.append(s + "\n");
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ArchivosGraficos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ArchivosGraficos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch(HeadlessException ae) {
            System.out.println(ae);
        }
    }//GEN-LAST:event_leerBtnActionPerformed

    private XYDataset createDataset() {  
        XYSeriesCollection dataset = new XYSeriesCollection();  
        
        XYSeries series1 = new XYSeries("Obrero 1"); 
        for (int i = 0; i < 15; i++) {
            series1.add(i + 1, obrero1[i]);
        }
        dataset.addSeries(series1);  
          
       XYSeries series2 = new XYSeries("Obrero 2"); 
        for (int i = 0; i < 15; i++) {
            series2.add(i + 1, obrero2[i]);
        }
        dataset.addSeries(series2);  
        
        XYSeries series3 = new XYSeries("Obrero 3"); 
        for (int i = 0; i < 15; i++) {
            series3.add(i + 1, obrero3[i]);
        }
        dataset.addSeries(series3);  
      
        return dataset;  
    }  
    
    
    private void organizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizarBtnActionPerformed
        // TODO add your handling code here:
        String datos = displayDatos.getText();
        System.out.println(datos);
        StringTokenizer st=new StringTokenizer(datos,"\n"+",");
        int iterador = 1;
        int contadorObreros1 = 0;
        int contadorObreros2 = 0;
        int contadorObreros3 = 0;
        while(st.hasMoreTokens()) {
            if (iterador == 1) {
                int obrero1Data = Integer.parseInt(st.nextToken());
                obrero1[contadorObreros1] = obrero1Data;
                iterador++;
                contadorObreros1++;
            } else if (iterador == 2) {
                obrero2[contadorObreros2] = Integer.parseInt(st.nextToken());
                iterador++;
                contadorObreros2++;
            } else if (iterador == 3) {
                obrero3[contadorObreros3] = Integer.parseInt(st.nextToken());
                iterador = 1;
                contadorObreros3++;
            }
        }
    }//GEN-LAST:event_organizarBtnActionPerformed
  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        XYDataset dataset = createDataset();  
      
        // Create chart  
        JFreeChart chart = ChartFactory.createScatterPlot(  
            "Obrerosss",   
            "X-Axis", 
            "Y-Axis", 
            dataset
        );
          
        //Changes background color  
        XYPlot plot = (XYPlot)chart.getPlot();  
        plot.setBackgroundPaint(new Color(255,228,196));  
          
         
        // Create Panel  
        ChartPanel panel = new ChartPanel(chart);  
        setContentPane(panel); 
        
        
        panel.setSize(800, 400);  
        panel.setVisible(true);  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void displayDatosCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_displayDatosCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_displayDatosCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArchivosGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArchivosGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArchivosGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArchivosGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArchivosGraficos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea displayDatos;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leerBtn;
    private javax.swing.JButton organizarBtn;
    // End of variables declaration//GEN-END:variables
}
