/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Usuario
 */
public class examenGraficas extends javax.swing.JFrame {
    
    int[] salarioMujeresEstado1  = new int[2];
    int[] salarioMujeresEstado24 = new int[2];
    int[] salarioMujeresEstado32 = new int[2];
    int[] salarioHombresEstado1  = new int[2];
    int[] salarioHombresEstado24 = new int[2];
    int[] salarioHombresEstado32 = new int[2];
    
    int[] temporal = new int[4];

    /**
     * Creates new form examenGraficas
     */
    public examenGraficas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        displayDatos = new javax.swing.JTextArea();
        leerBtn = new javax.swing.JButton();
        organizarBtn = new javax.swing.JButton();
        generarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayDatos.setColumns(20);
        displayDatos.setRows(5);
        jScrollPane1.setViewportView(displayDatos);

        leerBtn.setText("Leer Datos");
        leerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerBtnActionPerformed(evt);
            }
        });

        organizarBtn.setText("Organizar Datos");
        organizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizarBtnActionPerformed(evt);
            }
        });

        generarBtn.setText("Generar Gráfica");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(leerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(organizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(generarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(organizarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerBtnActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser open = new JFileChooser();
            int option = open.showOpenDialog(this);
            File f1 = new File(open.getSelectedFile().getPath());
            try (FileReader fr = new FileReader(f1)) {
                BufferedReader br = new BufferedReader(fr);
                String s;
                while((s=br.readLine())!=null) {
                    displayDatos.append(s + "\n");
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(examenGraficas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(examenGraficas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch(HeadlessException ae) {
            System.out.println(ae);
        }
    }//GEN-LAST:event_leerBtnActionPerformed

    private void organizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizarBtnActionPerformed
        // TODO add your handling code here:
        String datos = displayDatos.getText();
        // System.out.println(datos);
        StringTokenizer st = new StringTokenizer(datos, "\n");
        int iterador = 1;
        String hombre = (char)34 + "H" + (char)34;
        String mujer = (char)34 + "M" + (char)34;
        
        while(st.hasMoreTokens()) {
            StringTokenizer st2 = new StringTokenizer(st.nextToken(), ",");
            while(st2.hasMoreTokens()) {
                String actual = st2.nextToken();
                if (actual.equals(hombre)) {
                    System.out.println("Hombre -> " + actual);
                    System.out.println("Estado -> " + st2.nextToken());
                } else if (actual.equals(mujer)) {
                    System.out.println("Mujer -> " + actual);
                    System.out.println("Estado -> " + st2.nextToken());
                } else {
                    System.out.println("Dato -> " + actual);
                }
            }
        }        
    }//GEN-LAST:event_organizarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(examenGraficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(examenGraficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(examenGraficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(examenGraficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new examenGraficas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea displayDatos;
    private javax.swing.JButton generarBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leerBtn;
    private javax.swing.JButton organizarBtn;
    // End of variables declaration//GEN-END:variables
}
