/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graficasUI;

import javax.swing.SwingUtilities;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Usuario
 */
public class grafica2 extends javax.swing.JFrame {

        public grafica2(String title) {
        super(title);
        initComponents();
        // Create dataset  
        DefaultCategoryDataset dataset = createDataset();  
        // Create chart  
        JFreeChart chart = ChartFactory.createLineChart(  
            "Poblacion de cerezos", // Chart title  
            "Diametro del tronco en pulgadas", // X-Axis Label  
            "Altura del arbol en pies", // Y-Axis Label  
            dataset  
            );  
      
        ChartPanel panel = new ChartPanel(chart);  
        setContentPane(panel);
    }
    
    private DefaultCategoryDataset createDataset() {  
      
        String series1 = "Troncos";  
      
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();  
      
        dataset.addValue(8.3, series1, "70");  
        dataset.addValue(8.6, series1, "65");
        dataset.addValue(8.8, series1, "63");  
        dataset.addValue(10.5, series1, "72"); 
        dataset.addValue(10.7, series1, "81");  
        dataset.addValue(10.8, series1, "83"); 
        dataset.addValue(11.0, series1, "66");  
        dataset.addValue(11.0, series1, "75"); 
        dataset.addValue(11.1, series1, "80");  
        dataset.addValue(11.2, series1, "75"); 
        dataset.addValue(11.3, series1, "79");  
        dataset.addValue(11.4, series1, "76"); 
        dataset.addValue(11.4, series1, "76");  
        dataset.addValue(11.7, series1, "69"); 
        dataset.addValue(12.0, series1, "75");  
        dataset.addValue(12.9, series1, "74"); 
        dataset.addValue(12.9, series1, "85");  
        dataset.addValue(13.3, series1, "86"); 
        dataset.addValue(13.7, series1, "71");  
        dataset.addValue(13.8, series1, "64"); 
        dataset.addValue(14.0, series1, "78");  
        dataset.addValue(14.2, series1, "80"); 
        dataset.addValue(14.5, series1, "74");  
        dataset.addValue(16.0, series1, "72"); 
        dataset.addValue(16.3, series1, "77");  
        dataset.addValue(17.3, series1, "81"); 
        dataset.addValue(17.5, series1, "82");  
        dataset.addValue(17.9, series1, "80"); 
        dataset.addValue(18.0, series1, "80");  
        dataset.addValue(18.0, series1, "80"); 
        dataset.addValue(20.6, series1, "87");  
        
        

      
        return dataset;  
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> {
       grafica2 ejemplo = new grafica2("Población de Cerezos");
       ejemplo.setAlwaysOnTop(true);
       ejemplo.pack();
       ejemplo.setSize(600, 400);
       ejemplo.setDefaultCloseOperation(EXIT_ON_CLOSE);
       ejemplo.setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
