/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graficasUI;

import java.awt.Color;
import javax.swing.SwingUtilities;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Usuario
 */
public class grafica3 extends javax.swing.JFrame {

    /**
     * Creates new form grafica3
     * @param title
     */
    public grafica3(String title) {
        super(title);
        initComponents();
                // Create dataset  
        XYDataset dataset = createDataset();  
      
        // Create chart  
        JFreeChart chart = ChartFactory.createScatterPlot(  
            "comparison chart",   
            "X-Axis", "Y-Axis", dataset);  
      
          
        //Changes background color  
        XYPlot plot = (XYPlot)chart.getPlot();  
        plot.setBackgroundPaint(new Color(255,228,196));  
          
         
        // Create Panel  
        ChartPanel panel = new ChartPanel(chart);  
        setContentPane(panel);  

    }
    
          private XYDataset createDataset() {  
        XYSeriesCollection dataset = new XYSeriesCollection();  
      
        //Boys (Age,weight) series  
        XYSeries series1 = new XYSeries("a");  
        series1.add(1, 0.08);  
        series1.add(2, 0.22);  
        series1.add(3, 0.43);  
        series1.add(4, 0.55);  
        series1.add(5, 0.059);  
        series1.add(6, 0.084);  
        series1.add(7, 0.22);  
        series1.add(8, 0.43);  
        series1.add(9, 0.55);  
        series1.add(10, 0.059);  
      
        dataset.addSeries(series1);  
          
       //Girls (Age,weight) series  
        XYSeries series2 = new XYSeries("b");  
        series2.add(1, 0.45);  
        series2.add(2, 0.64);  
        series2.add(3, 0.15);  
        series2.add(4, 0.64);  
        series2.add(5, 0.38);  
        series2.add(6, 0.45);  
        series2.add(7, 0.64);  
        series2.add(8, 0.15);  
        series2.add(9, 0.64);  
        series2.add(10, 0.38);  
      
        dataset.addSeries(series2);  
      
        return dataset;  
      }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> {  
            grafica3 example = new grafica3("Scatter Chart Example");  
            example.setSize(800, 400);  
            example.setLocationRelativeTo(null);  
            example.setDefaultCloseOperation(EXIT_ON_CLOSE);  
            example.setVisible(true);  
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
