/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graficasUI;

import java.text.DecimalFormat;
import javax.swing.SwingUtilities;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.PieSectionLabelGenerator;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;

/**
 *
 * @author Usuario
 */
public class grafica5 extends javax.swing.JFrame {

     public grafica5(String title) {
        super(title);
        initComponents();
        // Create dataset  
        PieDataset dataset = createDataset();  
      
        // Create chart  
        JFreeChart chart = ChartFactory.createPieChart(  
            "Pie Chart Example",  
            dataset,  
            true,   
            true,  
            false);  
      
        //Format Label  
        PieSectionLabelGenerator labelGenerator = new StandardPieSectionLabelGenerator(  
            "Marks {0} : ({2})", new DecimalFormat("0"), new DecimalFormat("0%"));  
        ((PiePlot) chart.getPlot()).setLabelGenerator(labelGenerator);  
          
        // Create Panel  
        ChartPanel panel = new ChartPanel(chart);  
        setContentPane(panel);  

    }
    
    private PieDataset createDataset() {  
      
        DefaultPieDataset dataset=new DefaultPieDataset();  
        dataset.setValue("Africa", 52);  
        dataset.setValue("Americas", 25);  
        dataset.setValue("Asia", 33);  
        dataset.setValue("Europe", 30);  
        dataset.setValue("Oceania", 2);  
        return dataset;  
      }  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        SwingUtilities.invokeLater(() -> {  
            grafica5 example;  
            example = new grafica5("Pie Chart Example");
            example.setSize(800, 400);  
            example.setLocationRelativeTo(null);  
            example.setDefaultCloseOperation(EXIT_ON_CLOSE);  
            example.setVisible(true);  
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
