/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graficasUI;

import javax.swing.SwingUtilities;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Usuario
 */
public class grafica4 extends javax.swing.JFrame {
 /**
     * Creates new form grafica4
     */
    public grafica4(String appTitle) {
        super(appTitle);
        initComponents();
        // Create Dataset  
        CategoryDataset dataset = createDataset();  
          
        //Create chart  
        JFreeChart chart=ChartFactory.createBarChart(  
            "Bar Chart Example", //Chart Title  
            "Year", // Category axis  
            "Population in Million", // Value axis  
            dataset,  
            PlotOrientation.VERTICAL,  
            true,true,false  
           );  
      
        ChartPanel panel=new ChartPanel(chart);  
        setContentPane(panel);  

    }
    
    private CategoryDataset createDataset() {  
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();  
      
        dataset.addValue(11.7, "50-54", "Rural Male");
        dataset.addValue(18.1, "55-59", "Rural Male");  
        dataset.addValue(26.9, "60-64", "Rural Male");  
        dataset.addValue(41.0, "65-69", "Rural Male");  
        dataset.addValue(66.0, "70-74", "Rural Male");
        
        
        dataset.addValue(8.7, "50-54", "Rural Female");
        dataset.addValue(11.7, "55-59", "Rural Female");  
        dataset.addValue(20.3, "60-64", "Rural Female");  
        dataset.addValue(30.9, "65-69", "Rural Female");  
        dataset.addValue(54.3, "70-74", "Rural Female");
        
        
        dataset.addValue(15.4, "50-54", "Urban Male");
        dataset.addValue(24.3, "55-59", "Urban Male");  
        dataset.addValue(37.0, "60-64", "Urban Male");  
        dataset.addValue(54.6, "65-69", "Urban Male");  
        dataset.addValue(71.1, "70-74", "Urban Male");
        
        dataset.addValue(8.4, "50-54", "Urban Female");
        dataset.addValue(13.6, "55-59", "Urban Female");  
        dataset.addValue(19.3, "60-64", "Urban Female");  
        dataset.addValue(35.1, "65-69", "Urban Female");  
        dataset.addValue(50.0, "70-74", "Urban Female");
      
        return dataset;  
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
                SwingUtilities.invokeAndWait(()->{  
            grafica4 example=new grafica4("Bar Chart Window");  
            example.setSize(800, 400);  
            example.setLocationRelativeTo(null);  
            example.setDefaultCloseOperation(EXIT_ON_CLOSE);  
            example.setVisible(true);  
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
