/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda;

import java.awt.Container;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class AgendaUI extends javax.swing.JFrame {

    /**
     * Creates new form AgendaUI
     */
    
    JOptionPane casaPane, trabajoPane, kidsPane;
    String str, str2, str3;
    
    public AgendaUI() throws IOException {
        initComponents();
        try {
            BufferedReader br = new BufferedReader(new FileReader ("C:\\Users\\Usuario\\code\\school_code\\semester_03\\Lenguajes de Computacion 3\\agenda\\src\\trabajo.txt"));
            while ((str = br.readLine()) != null) {
                areaTrabajo.append(str+"\n");         
            } 
            br.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AgendaUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        trabajoPane = new JOptionPane("Guardar como trabajo.txt",
    	              JOptionPane.INFORMATION_MESSAGE,
    	              JOptionPane.YES_NO_OPTION, null);
        trabajoPane.setSelectionValues(null);

        try {
            BufferedReader br2 = new BufferedReader(new FileReader ("C:\\Users\\Usuario\\code\\school_code\\semester_03\\Lenguajes de Computacion 3\\agenda\\src\\casa.txt"));
            while ((str = br2.readLine()) != null) {
                areaCasa.append(str+"\n");         
            } 
            br2.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AgendaUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        casaPane = new JOptionPane("Guardar como casa.txt",
    	              JOptionPane.INFORMATION_MESSAGE,
    	              JOptionPane.YES_NO_OPTION, null);
        casaPane.setSelectionValues(null);
        
        try {
            BufferedReader br3 = new BufferedReader(new FileReader ("C:\\Users\\Usuario\\code\\school_code\\semester_03\\Lenguajes de Computacion 3\\agenda\\src\\niños.txt"));
            while ((str = br3.readLine()) != null) {
                areaKids.append(str+"\n");         
            } 
            br3.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AgendaUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        kidsPane = new JOptionPane("Guardar como niños.txt",
    	              JOptionPane.INFORMATION_MESSAGE,
    	              JOptionPane.YES_NO_OPTION, null);
        kidsPane.setSelectionValues(null);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTrabajo = new javax.swing.JTextArea();
        guardarTrabajo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaCasa = new javax.swing.JTextArea();
        guardarCasa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaKids = new javax.swing.JTextArea();
        guardarKids = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaTrabajo.setColumns(20);
        areaTrabajo.setRows(5);
        jScrollPane1.setViewportView(areaTrabajo);

        guardarTrabajo.setText("Guardar");
        guardarTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarTrabajoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(guardarTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Trabajo", jPanel1);

        areaCasa.setColumns(20);
        areaCasa.setRows(5);
        jScrollPane2.setViewportView(areaCasa);

        guardarCasa.setText("Guardar");
        guardarCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCasaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(guardarCasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarCasa, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Casa", jPanel2);

        areaKids.setColumns(20);
        areaKids.setRows(5);
        jScrollPane3.setViewportView(areaKids);

        guardarKids.setText("Guardar");
        guardarKids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarKidsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(guardarKids, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarKids, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Niños", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarTrabajoActionPerformed
        // TODO add your handling code here:
        Container parent = guardarTrabajo.getParent();
        JDialog jd = trabajoPane.createDialog(parent, " trabajo");
        jd.show();
        Integer i = (Integer)trabajoPane.getValue();
        int ii=i.intValue();
        if (ii == 0) {
            String trabajoText = areaTrabajo.getText();
            try {
                FileWriter fw = new FileWriter("C:\\Users\\Usuario\\code\\school_code\\semester_03\\Lenguajes de Computacion 3\\agenda\\src\\trabajo.txt");
                fw.write(trabajoText);
                fw.flush();
            } catch(IOException ioe) {
            
            }
        }
    }//GEN-LAST:event_guardarTrabajoActionPerformed

    private void guardarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCasaActionPerformed
        // TODO add your handling code here:
        Container parent = guardarCasa.getParent();
        JDialog jd = casaPane.createDialog(parent, " casa");
        jd.show();
        Integer i = (Integer)casaPane.getValue();
        int ii=i.intValue();
        if (ii == 0) {
            String trabajoText = areaCasa.getText();
            try {
                FileWriter fw = new FileWriter("C:\\Users\\Usuario\\code\\school_code\\semester_03\\Lenguajes de Computacion 3\\agenda\\src\\casa.txt");
                fw.write(trabajoText);
                fw.flush();
            } catch(IOException ioe) {
            
            }
        }
    }//GEN-LAST:event_guardarCasaActionPerformed

    private void guardarKidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarKidsActionPerformed
        // TODO add your handling code here:
        Container parent = guardarKids.getParent();
        JDialog jd = kidsPane.createDialog(parent, " niños");
        jd.show();
        Integer i = (Integer)kidsPane.getValue();
        int ii=i.intValue();
        if (ii == 0) {
            String trabajoText = areaKids.getText();
            try {
                FileWriter fw = new FileWriter("C:\\Users\\Usuario\\code\\school_code\\semester_03\\Lenguajes de Computacion 3\\agenda\\src\\niños.txt");
                fw.write(trabajoText);
                fw.flush();
            } catch(IOException ioe) {
            
            }
        }
    }//GEN-LAST:event_guardarKidsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AgendaUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(AgendaUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaCasa;
    private javax.swing.JTextArea areaKids;
    private javax.swing.JTextArea areaTrabajo;
    private javax.swing.JButton guardarCasa;
    private javax.swing.JButton guardarKids;
    private javax.swing.JButton guardarTrabajo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
