/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hangManInterfaces;

import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class hangManInterface extends javax.swing.JFrame {
    
    private int oportunidades;
    
    private final String[] palabras = {"casa", "orangutan", "programar"};
    private final String[] palabrasGuiones = {"_ _ _ _", "_ _ _ _ _ _ _ _ _", "_ _ _ _ _ _ _ _ _"};
    private String letrasUsadas = "";
    
    // random para la palabra
    Random rand = new Random();
    private final int randomNum = rand.nextInt((palabras.length - 0) + 1) + 0;
    
    private final String palabra = palabras[randomNum];
    private String palabraGuiones = palabrasGuiones[randomNum];
    
    private String userInput;
    private char userLetterInput;
    private int isLetterInWord;
    private int letterIndex;
    
    private String[] letrasPalabra;
    private String[] guionesPalabra;
    
    private int contadorLetras = 0;
    
    private int isLetterInLetters;

    /**
     * Creates new form hangManInterface
     */
    public hangManInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wordLabel = new javax.swing.JLabel();
        letrasUsadasLabel = new javax.swing.JLabel();
        letterInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        iniciarBtn = new javax.swing.JButton();
        resultadoLabel = new javax.swing.JLabel();
        advertenciasLabel = new javax.swing.JLabel();
        displayImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        wordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        wordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wordLabel.setText("Palabra: ");

        letrasUsadasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letrasUsadasLabel.setText("Letras Usadas: ");
        letrasUsadasLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        letterInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterInputActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingresar una letra: ");

        iniciarBtn.setText("Iniciar");
        iniciarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarBtnActionPerformed(evt);
            }
        });

        resultadoLabel.setText(" ");

        displayImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uihangman/oportunidades_8.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(letrasUsadasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(resultadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iniciarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letterInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(advertenciasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resultadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letrasUsadasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(letterInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(iniciarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(advertenciasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(displayImage, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wordLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void letterInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterInputActionPerformed
        // TODO add your handling code here:
        userInput = letterInput.getText();
        userLetterInput = userInput.charAt(0);
        isLetterInWord = palabra.indexOf(userLetterInput);
        advertenciasLabel.setText(""); 
        
        if (isLetterInWord == -1) {
            oportunidades--;

            if (oportunidades == 6) {
                ImageIcon ico7 = new ImageIcon(getClass().getResource("/uihangman/oportunidades_7.jpg"));
                displayImage.setIcon(ico7);
            } else if (oportunidades == 5) {
                ImageIcon ico6 = new ImageIcon(getClass().getResource("/uihangman/oportunidades_6.jpg"));
                displayImage.setIcon(ico6);
            } else if (oportunidades == 4) {
                ImageIcon ico5 = new ImageIcon(getClass().getResource("/uihangman/oportunidades_5.jpg"));
                displayImage.setIcon(ico5);
            } else if (oportunidades == 3) {
                ImageIcon ico4 = new ImageIcon(getClass().getResource("/uihangman/oportunidades_4.jpg"));
                displayImage.setIcon(ico4);
            } else if (oportunidades == 2) {
                ImageIcon ico3 = new ImageIcon(getClass().getResource("/uihangman/oportunidades_3.jpg"));
                displayImage.setIcon(ico3);
            } else if (oportunidades == 1) {
                ImageIcon ico2 = new ImageIcon(getClass().getResource("/uihangman/oportunidades_2.jpg"));
                displayImage.setIcon(ico2);
            } else if (oportunidades == 0) {
                letterInput.setEnabled(false);
                resultadoLabel.setText("Haz perdido, la palabra era: " + palabra);
                ImageIcon ico1 = new ImageIcon(getClass().getResource("/uihangman/oportunidades_1.jpg"));
                displayImage.setIcon(ico1);
            }
            letrasUsadas = letrasUsadas + " " + userInput;
            letrasUsadasLabel.setText("Letras Usadas: " + letrasUsadas);
            letterInput.setText("");
        } else {
            // revisar que la letra no este en las palabras usadas
            // ...
            isLetterInLetters = letrasUsadas.indexOf(userLetterInput);
                
            if (isLetterInLetters == -1) {
                letterIndex = isLetterInWord;
                letrasPalabra = palabra.split("");
                guionesPalabra = palabraGuiones.split(" ");
                for (int i = 0; i < letrasPalabra.length; i++) {
                    if (letrasPalabra[i].equals(userInput)) {
                    guionesPalabra[i] = userInput;
                    contadorLetras++;
                    }
                }
                String str1 = String.join(" ", guionesPalabra);
                palabraGuiones = str1;
                wordLabel.setText("Palabra: " + palabraGuiones);
                letrasUsadas = letrasUsadas + " " + userInput;
                letrasUsadasLabel.setText("Letras Usadas: " + letrasUsadas);
                letterInput.setText("");
                if (contadorLetras == palabra.length()) {
                    letterInput.setEnabled(false);
                    resultadoLabel.setText("Haz ganado!");
                    iniciarBtn.setEnabled(false);
                } 
            } else {
                advertenciasLabel.setText("Letra ya usada");
                letterInput.setText("");
            }
        }
    }//GEN-LAST:event_letterInputActionPerformed

    private void iniciarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarBtnActionPerformed
        // TODO add your handling code here:
        wordLabel.setText("Palabra: " + palabraGuiones);
        oportunidades = 7;
        iniciarBtn.setEnabled(false);
    }//GEN-LAST:event_iniciarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hangManInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hangManInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hangManInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hangManInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hangManInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advertenciasLabel;
    private javax.swing.JLabel displayImage;
    private javax.swing.JButton iniciarBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel letrasUsadasLabel;
    private javax.swing.JTextField letterInput;
    private javax.swing.JLabel resultadoLabel;
    private javax.swing.JLabel wordLabel;
    // End of variables declaration//GEN-END:variables
}
