/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nombresInterfaces;

import java.util.Random;

/**
 *
 * @author Usuario
 */
public class nombreInterface extends javax.swing.JFrame {

    /**
     * Creates new form nombreInterface
     */
    public nombreInterface() {
        initComponents();
    }
    
    private String[] nombres = {"Diego", "Alberto", "Maria", "Andrea", "Alejandro", "Sofia", "Angeles", "Juan", "Mar", "Fernando"};
    private String[] apellidos = {"Moreno", "Garcia", "Perez", "Sánchez", "Hernández", "Martinez", "López", "Rodríguez", "Cruz", "Flores"};
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generarDatosBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        datosArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        generarDatosBtn.setText("Generar Datos");
        generarDatosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarDatosBtnActionPerformed(evt);
            }
        });

        datosArea.setColumns(20);
        datosArea.setRows(5);
        jScrollPane1.setViewportView(datosArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(generarDatosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generarDatosBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarDatosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarDatosBtnActionPerformed
        // TODO add your handling code here:
        // random para la palabra
        Random rand = new Random();
        int randomNumNombre;
        int randomNumApellidoP;
        int randomNumApellidoM;
        String nombre;
        String apellidoP;
        String apellidoM;
        
        for (int i = 0; i < 100; i++) {
            randomNumNombre = rand.nextInt((9 - 0) + 1) + 0;
            randomNumApellidoP = rand.nextInt((9 - 0) + 1) + 0;
            randomNumApellidoM = rand.nextInt((9 - 0) + 1) + 0;
            nombre = nombres[randomNumNombre];
            apellidoP = apellidos[randomNumApellidoP];
            apellidoM = apellidos[randomNumApellidoM];
            datosArea.append(nombre + " " + apellidoP + " " + apellidoM + "\n");
        }
    }//GEN-LAST:event_generarDatosBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nombreInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nombreInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nombreInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nombreInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nombreInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea datosArea;
    private javax.swing.JButton generarDatosBtn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
