/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package archivosgraficastarea;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Usuario
 */
public class ArchivosGraficasUI extends javax.swing.JFrame {
    
    int cuentaMujeres = 0;
    int cuentaHombres = 0;
    String sexo;
    String estado;
    
    /**
     * Creates new form ArchivosGraficasUI
     */
    public ArchivosGraficasUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        generarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Leer Archivo 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Leer Archivo 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        generarBtn.setText("Generar Gráfica");
        generarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser open = new JFileChooser();
            int option = open.showOpenDialog(this);
            File f1 = new File(open.getSelectedFile().getPath());
            try (FileReader fr = new FileReader(f1)) {
                BufferedReader br = new BufferedReader(fr);
                String s;
                while((s=br.readLine())!=null) {
                    System.out.println(s);
                    StringTokenizer st = new StringTokenizer(s, "\n");
                    String hombre = (char)34 + "H" + (char)34;
                    String mujer = (char)34 + "M" + (char)34;
                    String estadoABuscar = "10";
                    String salarioABuscar = "888";
                    while(st.hasMoreTokens()) {
                        StringTokenizer st2 = new StringTokenizer(st.nextToken(), ",");
                        while(st2.hasMoreTokens()) {
                            String actual = st2.nextToken();
                            if (actual.equals(hombre)) {
                                sexo = actual;
                                estado = st2.nextToken();
                            } else if (actual.equals(mujer)) {
                                sexo = actual;
                                estado = st2.nextToken();
                            } else {
                                if (sexo.equals(mujer) && estado.equals(estadoABuscar)) {
                                    if (salarioABuscar.equals(actual)) {
                                        cuentaMujeres++;
                                    }
                                }  else if (sexo.equals(hombre) && estado.equals(estadoABuscar)) {
                                    if (salarioABuscar.equals(actual)) {
                                        cuentaHombres++;
                                    }
                                }
                            }
                        }
                    }    
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ArchivosGraficasUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ArchivosGraficasUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch(HeadlessException ae) {
            System.out.println(ae);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser open = new JFileChooser();
            int option = open.showOpenDialog(this);
            File f1 = new File(open.getSelectedFile().getPath());
            try (FileReader fr = new FileReader(f1)) {
                BufferedReader br = new BufferedReader(fr);
                String s;
                while((s=br.readLine())!=null) {
                    System.out.println(s);
                    StringTokenizer st = new StringTokenizer(s, "\n");
                    String hombre = (char)34 + "H" + (char)34;
                    String mujer = (char)34 + "M" + (char)34;
                    String estadoABuscar = "10";
                    String salarioABuscar = "888";
                    while(st.hasMoreTokens()) {
                        StringTokenizer st2 = new StringTokenizer(st.nextToken(), ",");
                        while(st2.hasMoreTokens()) {
                            String actual = st2.nextToken();
                            if (actual.equals(hombre)) {
                                sexo = actual;
                                estado = st2.nextToken();
                            } else if (actual.equals(mujer)) {
                                sexo = actual;
                                estado = st2.nextToken();
                            } else {
                                if (sexo.equals(mujer) && estado.equals(estadoABuscar)) {
                                    if (salarioABuscar.equals(actual)) {
                                        cuentaMujeres++;
                                    }
                                }  else if (sexo.equals(hombre) && estado.equals(estadoABuscar)) {
                                    if (salarioABuscar.equals(actual)) {
                                        cuentaHombres++;
                                    }
                                }
                            }
                        }
                    }    
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ArchivosGraficasUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ArchivosGraficasUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch(HeadlessException ae) {
            System.out.println(ae);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void generarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarBtnActionPerformed
        // TODO add your handling code here:
        
        CategoryDataset dataset = createDataset();  
        JFreeChart chart = ChartFactory.createBarChart(  
            "Salarios entre hombres y mujeres por estados", //Chart Title  
            "", // Category axis  
            "Salario promedio en MXN", // Value axis  
            dataset,  
            PlotOrientation.VERTICAL,  
            true,true,false  
        );
        
        //CategoryItemRenderer renderer = ((CategoryPlot)chart.getPlot()).getRenderer();
        // renderer.setBaseItemLabelGenerator(new StandardCategoryItemLabelGenerator());
        // renderer.setBaseItemLabelsVisible(true);
        // ItemLabelPosition position = new ItemLabelPosition(ItemLabelAnchor.OUTSIDE12, 
        //        TextAnchor.TOP_CENTER);
        //renderer.setBasePositiveItemLabelPosition(position);
        
      
        JFrame frame = new JFrame("Salarios entre hombres y mujeres por estados");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.add(new ChartPanel(chart));
        frame.setLocationByPlatform(true);
        frame.pack();
        frame.setVisible(true); 
    }//GEN-LAST:event_generarBtnActionPerformed

    private CategoryDataset createDataset() {  
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        // Estado 10
        dataset.addValue(cuentaMujeres, "Mujeres", "Estado 10");  
        dataset.addValue(cuentaHombres, "Hombres", "Estado 10");  
      
        return dataset;  
    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArchivosGraficasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArchivosGraficasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArchivosGraficasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArchivosGraficasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArchivosGraficasUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generarBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
