/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graficasUI;

import javax.swing.SwingUtilities;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Usuario
 */
public class grafica4 extends javax.swing.JFrame {

    /**
     * Creates new form grafica4
     */
    public grafica4(String appTitle) {
        super(appTitle);
        initComponents();
        // Create Dataset  
        CategoryDataset dataset = createDataset();  
          
        //Create chart  
        JFreeChart chart=ChartFactory.createBarChart(  
            "Bar Chart Example", //Chart Title  
            "Year", // Category axis  
            "Population in Million", // Value axis  
            dataset,  
            PlotOrientation.VERTICAL,  
            true,true,false  
           );  
      
        ChartPanel panel=new ChartPanel(chart);  
        setContentPane(panel);  

    }
    
    private CategoryDataset createDataset() {  
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();  
      
        // Population in 2005  
        dataset.addValue(10, "USA", "2005");  
        dataset.addValue(15, "India", "2005");  
        dataset.addValue(20, "China", "2005");  
      
        // Population in 2010  
        dataset.addValue(15, "USA", "2010");  
        dataset.addValue(20, "India", "2010");  
        dataset.addValue(25, "China", "2010");  
      
        // Population in 2015  
        dataset.addValue(20, "USA", "2015");  
        dataset.addValue(25, "India", "2015");  
        dataset.addValue(30, "China", "2015");  
      
        return dataset;  
    }  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     * @throws java.lang.Exception
     */
    public static void main(String args[]) throws Exception  {
        SwingUtilities.invokeAndWait(()->{  
            grafica4 example=new grafica4("Bar Chart Window");  
            example.setSize(800, 400);  
            example.setLocationRelativeTo(null);  
            example.setDefaultCloseOperation(EXIT_ON_CLOSE);  
            example.setVisible(true);  
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
